apiVersion: v1
kind: Service
metadata:
  name: ain
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: ain
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ain
  name: ain
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ain
  template:
    metadata:
      labels:
        app: ain
    spec:
      imagePullSecrets:
        - name: ainacr
      containers:
        - image: ainacr.azurecr.io/ain:0.10
          imagePullPolicy: IfNotPresent
          name: ain
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: 27b32f64-9df6-41df-9313-cea4f9dfe199
            - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
              value: Microsoft.ApplicationInsights.Profiler.AspNetCore

